services:
  nginx:
    image: nginx:stable
    container_name: chatbot-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mongo_mongo_net

networks:
  mongo_mongo_net:
    external: true